services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api

  api-postgres-db:
    image: postgres
    container_name: api-postgres-db
    restart: always
    volumes:
      - api_postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: api
    container_name: api
    expose:
      - "8080"
    environment:
      - PYTHONUNBUFFERED=1
      - FASTAPI_RELOAD=1
    depends_on:
      api-postgres-db:
        condition: service_healthy

volumes:
  api_postgres_db_data:
